### ISSUE TITLE
Write a manual for using CLI mode and high throughput mode

### ISSUE THREAD

**Issue by bocklund** [bocklund/ht-prl#17]
Write the following sections:

- [ ] Introduction (what this package is)
- [ ] Installation (of Python, MPWorks, and this project)
- [ ] CLI usage
- [ ] High-throughput usage
